import { NetworkProvider } from '@ton/blueprint';
import { Address, Cell, toNano } from '@ton/core';


export async function run(provider: NetworkProvider){
    await provider.sender().send({
        // init: {
        //     code: Cell.fromBase64('te6ccgECDgEAArAAART/APSkE/S88sgLAQIBYgIDAgLMBAUCA3pgDA0E9dkGOASS+B8ADoaYGAuNhJL4HwfSB9IBj9ABi465D9ABj9ABh2omh9AH0gamoYA2mPkOAARxAtmZrBDHRqUogAKhmh+AUsUCGJ5CgCfQEsZ4tmZmT2qnBpn8EIPe7L7ykYXXGBQQgWO1y5qRhdcYEYmpuTYAHxgRgC4AJAYHCAkA6bXwUKiGJuCoQCaoKAeQoAn0BLGeLAOeLZmSRZGWAiXoAegBlgGSQfIA4OmRlgWUD5f/k6DhkZY/kuLhBCAvGoozkZY/ln6gC/QES54soAueLEf0BCeWACeZku8AMZGWCqAHni0EE5OHAfQEJZbWJZmZkuP2AQHAMjU3BvoA+kD4KFQSCHBUIBNUFAPIUAT6AljPFgHPFszJIsjLARL0APQAywDJ+QBwdMjLAsoHy//J0FAGxwXy4EoSoQNBVMhQBPoCWM8WzMzJ7VT6QDAg1wsBwwCRW+MNCgH8bEKCCJiWgBOgFbzy4Ev6QNMAMJXIIc8WyZFt4oIQ0XNUAHCAGMjLBVAFzxYk+gIUy2oTyx8Uyz8j+kQwcLqOM/goRANwVCATVBQDyFAE+gJYzxYBzxbMySLIywES9AD0AMsAyfkAcHTIywLKB8v/ydDPFpZsInABywHi9ADJCwAwNhPHBfLgSfpAMFrIUAT6AljPFszMye1UAEKOGFEkxwXy4EnUMEMDyFAE+gJYzxbMzMntVOBfBYQP8vAAPoIQ1TJ223CAEMjLBVADzxYi+gISy2rLH8s/yYBC+wAACIBA+wAAfa289qJofQB9IGpqGDYY/BQAuCoQCaoKAeQoAn0BLGeLAOeLZmSRZGWAiXoAegBlgGT8gDg6ZGWBZQPl/+ToQAAfrxb2omh9AH0gamoYP6qQQA=='),
        // },
                        body: Cell.fromHex('te6cckECEwEAA28AAgE0AgEBhwgAXiffopr7/k9Xt7rBhWft8TdXbYlzdK5HOq23dIWQwE0APNbBjCly/EahDXAD7/Nn7EaiM0ycL3Ul2XEJ2kkPLUegAgEU/wD0pBP0vPLICwMCAWIEBQICzAYHABug9gXaiaH0AfSB9IGoYQIB1AgJAgEgCgsAwwgxwCSXwTgAdDTAwFxsJUTXwPwDOD6QPpAMfoAMXHXIfoAMfoAMHOptAAC0x+CEA+KfqVSILqVMTRZ8AngghAXjUUZUiC6ljFERAPwCuA1ghBZXwe8upNZ8AvgXwSED/LwgABE+kQwcLry4U2ACASAMDQCD1AEGuQ9qJofQB9IH0gahgCaY/BCAvGooypEF1BCD3uy+8J3QlY+XFi6Z+Y/QAYCdAoEeQoAn0BLGeLAOeLZmT2qkAfFQPTP/oA+kAh8AHtRND6APpA+kDUMFE2oVIqxwXy4sEowv/y4sJUNEJwVCATVBQDyFAE+gJYzxYBzxbMySLIywES9AD0AMsAySD5AHB0yMsCygfL/8nQBPpA9AQx+gAg10nCAPLixHeAGMjLBVAIzxZw+gIXy2sTzIDgIBIA8QAJ6CEBeNRRnIyx8Zyz9QB/oCIs8WUAbPFiX6AlADzxbJUAXMI5FykXHiUAioE6CCCcnDgKAUvPLixQTJgED7ABAjyFAE+gJYzxYBzxbMye1UAvc7UTQ+gD6QPpA1DAI0z/6AFFRoAX6QPpAU1vHBVRzbXBUIBNUFAPIUAT6AljPFgHPFszJIsjLARL0APQAywDJ+QBwdMjLAsoHy//J0FANxwUcsfLiwwr6AFGooYIImJaAZrYIoYIImJaAoBihJ5cQSRA4N18E4w0l1wsBgERIA1ztRND6APpA+kDUMAfTP/oA+kAwUVGhUknHBfLiwSfC//LiwgWCCTEtAKAWvPLiw4IQe92X3sjLHxXLP1AD+gIizxYBzxbJcYAYyMsFJM8WcPoCy2rMyYBA+wBAE8hQBPoCWM8WAc8WzMntVIABwUnmgGKGCEHNi0JzIyx9SMMs/WPoCUAfPFlAHzxbJcYAQyMsFJM8WUAb6AhXLahTMyXH7ABAkECMAfMMAI8IAsI4hghDVMnbbcIAQyMsFUAjPFlAE+gIWy2oSyx8Syz/JcvsAkzVsIeIDyFAE+gJYzxYBzxbMye1Uz0HN3Q=='),
                        to: Address.parse('EQDzWwYwpcvxGoQ1wA-_zZ-xGojNMnC91JdlxCdpJDy1HpR-'),
                        value: toNano('0.05'),
                        bounce: true,

    })

}